### ISSUE TITLE
Can't open existing h2.db

### ISSUE THREAD

**Issue by henryken** [ccavanaugh/jgnash#48]
## Expected Behavior
Able to open the DB successfully

## Actual Behavior
"Invalid password or tried to open the wrong file type"

## Steps to Reproduce the Problem

  1. Open existing H2 DB with new version 2.34.1
  2. "Invalid password or tried to open the wrong file type"
  3.

## Specifications

  - jGnash Version: 2.34.1
  - Operating System: Windows 10
  - Java Version 1.8

**Comment by ccavanaugh** [comment]
Two options.. open the last backup (zipped file), or revert back a release, save as an XML or simple binary file and it will open correctly in the new release.  From there, you can save back to an H2 database.

I'm going to post a more detailed message in the user and devel Google Groups list today.

Root cause is your file is still using the old database schema and it takes manual intervention to upgrade.  The ability it handle the old schema broke in this last release.
