### ISSUE TITLE
Exe launcher fails when JDK 11 is present

### ISSUE THREAD

**Issue by valnaumov** [ccavanaugh/jgnash#66]
## Actual Behavior
jGnashFx.exe does not launch the app starting 2.35.0, although the bat script does. 

## Specifications

  - jGnash Version: starting 2.35.0
  - Operating System: Windows 10
  - Java Version: 1.8.0_181

JDK 11.0.1 is also installed on the system. If I rename the JDK folder, it works. Could you point to what has changed in the packaging process in 2.35.0?

I hope to see a bundled JRE with the app with the comming of Java 9. I don't mind extra 100MB.

**Comment by ccavanaugh** [comment]
More than likely, its caused by JavaFx not being installed as it was separated in Java 11.  Manual installation and running against the 3.0-dev branch should work.

The 3.0-dev branch is a work in process that will address this long term.  I'm sorting out a new reporting interface to replace the old API rot caused by jasperreports and itext that is preventing migration to Java 11.

I do intend to have jGnash download the JavaFx dependency automatically because it's platform dependent.  I'm not certain about bundling a JRE yet simply because I cannot build an OSX release at this time.

**Comment by valnaumov** [comment]
>  Manual installation and running against the 3.0-dev branch should work.
I hoped to run with JRE 8. Can it be configured for launch4j? 

Are you targeting JDK 11 on 3.0-dev? What problems are you facing with bundling on OSX? Maybe I could help.

**Comment by ccavanaugh** [comment]
3.0.0 has been released

**Comment by valnaumov** [comment]
Great! That solved the issue!
